#!/usr/bin/env bash

# Getting subdomain information
get_subdomain_info() {
    local subdomain=$1
    local domain=$2
    local full_domain="${subdomain}.${domain}"
    local result=$(dig +short "$full_domain")
    if [ -z "$result" ]; then
        echo "The subdomain $subdomain does not exist."
    else
        echo "The subdomain $subdomain is a A record and points to $result"
    fi
}

# Main logic
domain=$1
subdomain=$2

if [ -z "$domain" ]; then
    echo "Domain is required."
    exit 1
fi

if [ -z "$subdomain" ]; then
    # Default subdomains to check
    subdomains=("www" "lb-01" "web-01" "web-02")
    for sub in "${subdomains[@]}"; do
        get_subdomain_info "$sub" "$domain"
    done
else
    get_subdomain_info "$subdomain" "$domain"
fi
