#!/usr/bin/env bash
# Function to display usage message
usage() {
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

# Check if number of parameters is less than 4
if [ "$#" -lt 4 ]; then
    usage
    exit 1
fi

# Parameters
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

# Disable strict host key checking for scp
export SCP_OPTS="-o StrictHostKeyChecking=no"

# Transfer file using scp
scp -i "$PATH_TO_SSH_KEY" $SCP_OPTS "$PATH_TO_FILE" "$USERNAME@$IP":~/ || { echo "Error: File transfer failed."; exit 1; }

# Check if transfer was successful by listing files in home directory on the server
ssh -i "$PATH_TO_SSH_KEY" $SCP_OPTS "$USERNAME@$IP" 'ls ~/'
