#!/usr/bin/env bash

#printing "Best School" 10 times with a special condition for the 9th iteration

count=0

# Using a while loop to display "Best School" 10 times
while [ $count -lt 10 ]; do
    if [ $count -eq 8 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    (( count++ ))
done
